[tool.poetry]
name = "roubo-de-renda-calc"
version = "0.1.0"
description = ""
authors = ["Paulo Moggi <paulohpmoggi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.9"
black = "^22.3.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
